# Generated by Django 3.2 on 2024-06-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_unique_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user',
        ),
    ]
